version: '3.8'

services:
  anki-card-creator:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: anki-card-creator
    env_file:
      - .env
    ports:
      # Map container port to host port on all interfaces
      - "7860:7860"
    networks:
      - anki-network
    restart: unless-stopped

networks:
  anki-network:
    driver: bridge
